export enum PeriodType {
    SUBSCRIPTION = "SUBSCRIPTION",
    AVALIATION = "AVALIATION",
    RESUBSCRIPTION = "RESUBSCRIPTION",
    REAVALIATION = "REAVALIATION",
    FINAL = "FINAL",
    INACTIVE = "INACTIVE"
}
