export enum EvaluationCriterionName {
  CREATIVITY = "CREATIVITY",
  ORIGINALITY = "ORIGINALITY",
  UTILITY = "UTILITY",
  FEASIBILITY = "FEASIBILITY",
  IMPACT = "IMPACT",
  STRATEGIC_ALIGNMENT = "STRATEGIC_ALIGNMENT",
  CLARITY = "CLARITY",
  TECHNICAL_FEASIBILITY = "TECHNICAL_FEASIBILITY",
  INNOVATION = "INNOVATION",
}
